[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["simopt", "simopt.gui", "simopt.models", "simopt.solvers"]

[project]
name = "simoptlib"
version = "1.1.1"
authors = [
  { name="David Eckman", email="eckman@tamu.edu" },
  { name="Shane Henderson", email="sgh9@cornell.edu" },
  { name="Sara Shashaani", email="sshasha2@ncsu.edu" },
  { name="William Grochocinski", email="wagrocho@ncsu.edu" },
]
description = "A testbed for simulation-optimization experiments."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9,<3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
  "pandas",
  "seaborn",
  "mrg32k3a"
]

[project.optional-dependencies]
dev = [
  "sphinx",
]

[project.urls]
"Homepage" = "https://github.com/simopt-admin/simopt"
"Documentation" = "https://simopt.readthedocs.io/en/latest/"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "N", "UP", "ANN0", "ANN2", "ANN4", "ASYNC", "A", "RUF", "NPY201"]

[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["classproperty"]