{% set name = "simoptlib" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/simoptlib-{{ version }}.tar.gz
  sha256: a46b3ad0c49604af94d859737e6b1291a7ecb64c292725b7eb3de4ac8ae1b6aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=61.0
    - pip
  run:
    - python
    - numpy >=1.21.6
    - scipy >=1.7.3
    - matplotlib-base >=3.2.2
    - pandas >=1.3.5
    - seaborn >=0.11.2
    - mrg32k3a >=2.0.0

test:
  imports:
    - simopt
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A testbed for simulation-optimization experiments.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cenwangumass
